export const USER_VERIFIED = 'USER_VERIFIED';
export const VERIFICATION_REQUESTED = 'VERIFICATION_REQUESTED';

export const USER_LOGINING = 'USER_LOGINING';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_REGISTERING = 'USER_REGISTERING';
export const USER_REGISTERED = 'USER_REGISTERED';
