version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout
      - run: npm install
      - run: npm run prebuild
      - run: npm run build
  test:
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2.1
  build_test:
    jobs:
      - build
      - test
